export { default as Home } from './Home'
export { default as Info } from './Info'
export { default as Check } from './Check'
export { default as LoginRegister } from './LoginRegister'
export { default as Map } from './Map'
export { default as UserMenu } from './UserMenu'