export { default as Home } from './Home'
export { default as About } from './About'
export { default as Check } from './Check'
export { default as LoginRegister } from './LoginRegister'
export { default as Map } from './Map'
export { default as UserMenu } from './UserMenu'
export { default as Chatbot } from './Chatbot'