---
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: always
trailingComma: es5
proseWrap: preserve
htmlWhitespaceSensitivity: css
